import { Mona_Sans, Geist } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth-provider";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const mona = Mona_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Loopy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${mona.className} antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
