import { Mona_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth-provider";

const mona = Mona_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Loopy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mona.className} antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
