version: "3.8"

services:
  # Gateway
  gateway:
    build: ./services/gateway
    container_name: loopy-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # URLs for the microservices
      - AUTH_SERVICE_URL=http://auth-service:5001
      - PROJECT_SERVICE_URL=http://project-service:5002
    depends_on:
      - auth-service
      - project-service
    networks:
      - loopy-net

  # Auth Service
  auth:
    build: ./services/auth
    container_name: loopy-auth
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/loopy_auth_db
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongo
    networks:
      - loopy-net

  # 3. Project Service
  project-service:
    build: ./services/project
    container_name: loopy-project
    restart: always
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/loopy_project_db
      - JWT_SECRET=super_secret_shared_key_123
    depends_on:
      - mongo
    networks:
      - loopy-net

  # Database
  mongo:
    image: mongo:latest
    container_name: loopy-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - loopy-net

volumes:
  mongo_data:

networks:
  loopy-net:
    driver: bridge
