import type { Task, Milestone, CalendarEvent, Project, Activity, User } from "./types"

// Mock users
export const mockUsers: User[] = [
  { id: "1", name: "John Doe", email: "john@example.com", avatar: "JD", role: "project-manager" },
  { id: "2", name: "Jane Smith", email: "jane@example.com", avatar: "JS", role: "team-lead" },
  { id: "3", name: "Mike Johnson", email: "mike@example.com", avatar: "MJ", role: "team-member" },
  { id: "4", name: "Sarah Wilson", email: "sarah@example.com", avatar: "SW", role: "team-member" },
]

// Mock current user (for role-based views)
export const currentUser: User = mockUsers[0]

// Mock project
export const mockProject: Project = {
  id: "1",
  name: "Project Name",
  description: "Oh oh, very empty...",
  owner: mockUsers[0],
  startDate: "2025-09-21",
  endDate: "2026-04-30",
  color: "#EF4444",
  members: mockUsers,
  stats: {
    completed: 0,
    created: 8,
    updated: 8,
    dueSoon: 4,
  },
}

// Mock tasks
export const mockTasks: Task[] = [
  {
    id: "T-001",
    title: "Task Label",
    description: "This is a task description",
    status: "done",
    type: "task",
    priority: "high",
    assignee: mockUsers[0],
    dueDate: "2025-10-30",
    milestoneId: "M-001",
    projectId: "1",
    createdAt: "2025-10-01",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-002",
    title: "Task Label",
    status: "in-progress",
    type: "task",
    priority: "medium",
    assignee: mockUsers[1],
    dueDate: "2025-10-28",
    milestoneId: "M-001",
    projectId: "1",
    createdAt: "2025-10-02",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-003",
    title: "Task Label",
    status: "todo",
    type: "task",
    priority: "low",
    assignee: mockUsers[2],
    dueDate: "2025-10-30",
    milestoneId: "M-001",
    projectId: "1",
    createdAt: "2025-10-03",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-004",
    title: "Task Label",
    status: "todo",
    type: "bug",
    priority: "high",
    assignee: mockUsers[3],
    dueDate: "2025-10-30",
    milestoneId: "M-001",
    projectId: "1",
    createdAt: "2025-10-04",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-005",
    title: "Task Label",
    status: "todo",
    type: "feature",
    priority: "medium",
    assignee: mockUsers[0],
    dueDate: "2025-10-30",
    milestoneId: "M-001",
    projectId: "1",
    createdAt: "2025-10-05",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-006",
    title: "Task Label",
    status: "done",
    type: "task",
    priority: "low",
    assignee: mockUsers[1],
    projectId: "1",
    createdAt: "2025-10-06",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-007",
    title: "Task Label",
    status: "in-progress",
    type: "task",
    priority: "medium",
    assignee: mockUsers[2],
    projectId: "1",
    createdAt: "2025-10-07",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-008",
    title: "Task Label",
    status: "todo",
    type: "task",
    priority: "high",
    assignee: mockUsers[3],
    projectId: "1",
    createdAt: "2025-10-08",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-009",
    title: "Task Label",
    status: "todo",
    type: "story",
    priority: "low",
    assignee: mockUsers[0],
    projectId: "1",
    createdAt: "2025-10-09",
    updatedAt: "2025-10-14",
  },
  {
    id: "T-010",
    title: "Task Label",
    status: "todo",
    type: "task",
    priority: "medium",
    assignee: mockUsers[1],
    projectId: "1",
    createdAt: "2025-10-10",
    updatedAt: "2025-10-14",
  },
]

// Mock milestones
export const mockMilestones: Milestone[] = [
  {
    id: "M-001",
    name: "Milestone Name",
    description: "",
    startDate: "2025-10-14",
    dueDate: "2025-10-28",
    assignee: mockUsers[0],
    tasks: mockTasks.filter((t) => t.milestoneId === "M-001"),
    projectId: "1",
  },
  {
    id: "M-002",
    name: "Milestone Name",
    description: "",
    startDate: "2025-09-01",
    dueDate: "2025-09-15",
    assignee: mockUsers[1],
    tasks: [],
    projectId: "1",
  },
  {
    id: "M-003",
    name: "Milestone Name",
    description: "",
    startDate: "2025-10-01",
    dueDate: "2025-10-20",
    assignee: mockUsers[2],
    tasks: [],
    projectId: "1",
  },
  {
    id: "M-004",
    name: "Milestone Name",
    description: "",
    startDate: "2025-11-01",
    dueDate: "2025-11-30",
    assignee: mockUsers[3],
    tasks: [],
    projectId: "1",
  },
  {
    id: "M-005",
    name: "Milestone Name",
    description: "",
    startDate: "2025-11-15",
    dueDate: "2025-12-15",
    assignee: mockUsers[0],
    tasks: [],
    projectId: "1",
  },
  {
    id: "M-006",
    name: "Milestone Name",
    description: "",
    startDate: "2025-10-10",
    dueDate: "2025-11-10",
    assignee: mockUsers[1],
    tasks: [],
    projectId: "1",
  },
  {
    id: "M-007",
    name: "Milestone Name",
    description: "",
    startDate: "2025-12-01",
    dueDate: "2025-12-31",
    assignee: mockUsers[2],
    tasks: [],
    projectId: "1",
  },
  {
    id: "M-008",
    name: "Milestone Name",
    description: "",
    startDate: "2025-10-20",
    dueDate: "2025-11-20",
    assignee: mockUsers[3],
    tasks: [],
    projectId: "1",
  },
]

// Mock calendar events (converted from tasks and milestones for calendar display)
export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "E-001",
    title: "Milestone Name",
    type: "milestone",
    status: "in-progress",
    startDate: "2025-10-05",
    endDate: "2025-10-11",
    projectId: "1",
  },
  {
    id: "E-002",
    title: "Task La...",
    type: "task",
    status: "todo",
    startDate: "2025-10-02",
    endDate: "2025-10-04",
    projectId: "1",
  },
  {
    id: "E-003",
    title: "Meeting Recording...",
    type: "meeting",
    status: "done",
    startDate: "2025-10-06",
    projectId: "1",
  },
  {
    id: "E-004",
    title: "Task Label",
    type: "task",
    status: "done",
    startDate: "2025-10-06",
    projectId: "1",
  },
  {
    id: "E-005",
    title: "Task Label",
    type: "task",
    status: "in-progress",
    startDate: "2025-10-06",
    projectId: "1",
  },
  {
    id: "E-006",
    title: "Milestone Name",
    type: "milestone",
    status: "in-progress",
    startDate: "2025-10-05",
    endDate: "2025-10-11",
    projectId: "1",
  },
  {
    id: "E-007",
    title: "Meeting Recording...",
    type: "meeting",
    status: "done",
    startDate: "2025-10-20",
    projectId: "1",
  },
  {
    id: "E-008",
    title: "Meeting Recording...",
    type: "meeting",
    status: "done",
    startDate: "2025-10-20",
    projectId: "1",
  },
  {
    id: "E-009",
    title: "Meeting Recording...",
    type: "meeting",
    status: "done",
    startDate: "2025-10-24",
    projectId: "1",
  },
  {
    id: "E-010",
    title: "Meeting Recording...",
    type: "meeting",
    status: "done",
    startDate: "2025-10-24",
    projectId: "1",
  },
]

// Mock activities
export const mockActivities: Activity[] = [
  {
    id: "A-001",
    type: "file",
    user: "John",
    action: "updated file:",
    target: "Scope.docx",
    time: "2 hours ago",
    icon: "file",
    color: "bg-amber-500",
  },
  {
    id: "A-002",
    type: "meeting",
    action: "Meeting scheduled for tomorrow",
    time: "4 hours ago",
    icon: "calendar",
    color: "bg-blue-500",
  },
  {
    id: "A-003",
    type: "task",
    user: "Mike",
    action: "assigned new task to you",
    target: "Task Name",
    time: "6 hours ago",
    icon: "check",
    color: "bg-red-500",
  },
]
